"""FastAPI routes exposing NLP-powered player scouting features."""
from __future__ import annotations

from typing import List, Optional

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel, Field

from scouting_ml.nlp.role_classifier import classify_player_role
from scouting_ml.services.player_similarity_service import find_similar_players
from scouting_ml.services.scouting_report_service import get_scouting_report

router = APIRouter(prefix="/players", tags=["players_nlp"])


class ScoutingReportResponse(BaseModel):
    """Response model for a player scouting report."""

    player_id: str = Field(..., description="Player identifier")
    report: str = Field(..., description="Generated scouting report text")


class SimilarPlayer(BaseModel):
    """Similar player entry with score and justification."""

    player_id: str = Field(..., description="Similar player identifier")
    score: float = Field(..., description="Similarity score from FAISS index")
    justification: str = Field(..., description="Deterministic metadata-based reasoning")


class RoleResponse(BaseModel):
    """Response model for player role classification."""

    role: Optional[str] = Field(None, description="Predicted role label or null when low confidence")
    confidence: float = Field(..., description="Model confidence for the predicted role")


@router.get(
    "/{player_id}/scouting-report",
    response_model=ScoutingReportResponse,
    summary="Generate a scouting report for a player",
)
def scouting_report(player_id: str) -> ScoutingReportResponse:
    """Return a human-readable scouting report generated by the NLP summarizer."""
    try:
        report = get_scouting_report({"player_id": player_id})
    except ValueError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    except Exception as exc:  # pragma: no cover - defensive
        raise HTTPException(status_code=500, detail=f"Failed to generate report: {exc}") from exc
    return ScoutingReportResponse(player_id=player_id, report=report)


@router.get(
    "/{player_id}/similar",
    response_model=List[SimilarPlayer],
    summary="Find similar players",
)
def similar_players(player_id: str, top_k: int = Query(5, ge=1, le=50)) -> List[SimilarPlayer]:
    """Return similar players using the FAISS-backed similarity service."""
    try:
        results = find_similar_players(player_id, top_k=top_k)
    except ValueError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    except Exception as exc:  # pragma: no cover - defensive
        raise HTTPException(status_code=500, detail=f"Failed to fetch similar players: {exc}") from exc
    return [SimilarPlayer(**item) for item in results]


@router.get(
    "/{player_id}/role",
    response_model=RoleResponse,
    summary="Classify player role via zero-shot NLP",
)
def player_role(player_id: str) -> RoleResponse:
    """Return zero-shot role classification with confidence."""
    try:
        result = classify_player_role({"player_id": player_id})
    except ValueError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    except Exception as exc:  # pragma: no cover - defensive
        raise HTTPException(status_code=500, detail=f"Failed to classify role: {exc}") from exc
    return RoleResponse(role=result.get("role"), confidence=float(result.get("confidence", 0.0)))
