import type { ActivityItem, KPI, Player, PlayerPosition, ReportBlock, Shortlist, TaskItem, TeamCard } from "@/lib/types";

const createTrend = (base: number, variance: number, labels = ["Aug", "Sep", "Oct", "Nov", "Dec", "Jan"]) =>
  labels.map((label, index) => ({ label, value: Math.max(45, Math.min(99, base + Math.round(Math.sin(index) * variance) + index)) }));

const createMarketTrend = (start: number, step: number, labels = ["Aug", "Sep", "Oct", "Nov", "Dec", "Jan"]) =>
  labels.map((label, index) => ({ label, value: Number((start + index * step).toFixed(1)) }));

const createMatchLogs = (opponents: string[], seed: number) =>
  opponents.map((opponent, index) => ({
    opponent,
    date: `2025-0${Math.min(index + 2, 9)}-${String(6 + index).padStart(2, "0")}`,
    rating: Number((6.8 + ((seed + index) % 5) * 0.28).toFixed(1)),
    minutes: 70 + ((seed + index) % 3) * 10,
    goals: index % 3 === 0 ? 1 : 0,
    assists: index % 4 === 0 ? 1 : 0,
    progressivePasses: 5 + ((seed + index) % 6),
    duelsWon: 4 + ((seed + index) % 5),
  }));

const buildPlayer = (player: Player): Player => player;

export const players: Player[] = [
  buildPlayer({
    id: "p1",
    slug: "mika-van-den-bos",
    name: "Mika van den Bos",
    age: 21,
    nationality: "Netherlands",
    club: "FC Utrecht",
    league: "Eredivisie",
    position: "FB",
    secondaryPositions: ["W", "CB"],
    minutes: 2240,
    marketValueM: 6.5,
    scoutingScore: 92,
    form: "Rising",
    contractExpiry: "2027-06-30",
    preferredFoot: "Right",
    heightCm: 181,
    status: "priority",
    archetype: "Progressive wing-back",
    summary: "Aggressive carrier with repeatable final-third access and enough defensive volume to play early for a possession side.",
    strengths: ["Ball carrying", "Transition defending", "Volume crossing", "High-intensity repeat runs"],
    concerns: ["Back-post aerials", "Tendency to overplay in zone 14"],
    report: {
      technical: "Sharp first touch in motion, confident over distance, and able to deliver early diagonals under pressure.",
      tactical: "Best in a fullback role with freedom to overlap. Reads pressing triggers quickly and supports circulation on the outside lane.",
      physical: "Explosive first five metres and very good repeat sprint capacity. Still has room to add upper-body strength.",
      mental: "Demands the ball, recovers after mistakes quickly, and appears comfortable in high-tempo matches.",
      recommendation: "Pursue",
    },
    tags: ["U23", "Non-Big5", "High progression"],
    radar: [
      { subject: "Progression", value: 90 },
      { subject: "Creation", value: 83 },
      { subject: "Defending", value: 71 },
      { subject: "Physical", value: 84 },
      { subject: "Decision-making", value: 76 },
      { subject: "Press resistance", value: 81 },
    ],
    percentiles: [
      { label: "Progressive carries", value: 94, tone: "blue" },
      { label: "Final-third entries", value: 88, tone: "green" },
      { label: "Cross completion", value: 76, tone: "amber" },
      { label: "Defensive duels", value: 68 },
      { label: "Recovery pace", value: 91, tone: "green" },
    ],
    performanceSplit: [
      { category: "Attacking", current: 79, benchmark: 66 },
      { category: "Passing", current: 81, benchmark: 72 },
      { category: "Defending", current: 69, benchmark: 63 },
      { category: "Physical", current: 84, benchmark: 70 },
    ],
    trend: createTrend(74, 7),
    marketTrend: createMarketTrend(4.2, 0.45),
    matchLogs: createMatchLogs(["PSV", "AZ", "Twente", "Feyenoord", "Heerenveen"], 2),
    similarityIds: ["p4", "p6", "p8"],
    scoutNotes: [
      { author: "L. De Smet", note: "Explosive enough for Championship profile, but passing ceiling suits better sides.", time: "2h ago" },
      { author: "A. Mertens", note: "Strong upside if he can cut low-value turnovers when receiving inside.", time: "Yesterday" },
    ],
  }),
  buildPlayer({
    id: "p2",
    slug: "joao-serrano",
    name: "João Serrano",
    age: 22,
    nationality: "Portugal",
    club: "Vitória SC",
    league: "Primeira Liga",
    position: "DM",
    secondaryPositions: ["CM"],
    minutes: 2488,
    marketValueM: 7.8,
    scoutingScore: 89,
    form: "Stable",
    contractExpiry: "2026-06-30",
    preferredFoot: "Right",
    heightCm: 184,
    status: "shortlist",
    archetype: "Tempo-setting ball winner",
    summary: "Defensive midfielder with strong regain profile, clean first pass, and enough composure to anchor a pressing midfield.",
    strengths: ["Counterpressing", "Short-range circulation", "Duel timing", "Tempo control"],
    concerns: ["Limited final-third punch", "Can get isolated in wide coverage"],
    report: {
      technical: "Reliable one and two-touch player who rarely kills tempo and consistently finds the next free option.",
      tactical: "Understands rest-defence shapes and screens the back line well. Better as the deeper pivot than as a box-to-box eight.",
      physical: "Good engine and decent contact balance, but not an explosive accelerator over longer distances.",
      mental: "Plays with authority, communicates often, and looks comfortable in structurally demanding phases.",
      recommendation: "Pursue",
    },
    tags: ["Contract pressure", "Press resistant", "Midfield anchor"],
    radar: [
      { subject: "Progression", value: 77 },
      { subject: "Creation", value: 62 },
      { subject: "Defending", value: 91 },
      { subject: "Physical", value: 79 },
      { subject: "Decision-making", value: 88 },
      { subject: "Press resistance", value: 85 },
    ],
    percentiles: [
      { label: "Interceptions", value: 92, tone: "green" },
      { label: "Progressive passes", value: 81, tone: "blue" },
      { label: "Turnover avoidance", value: 87, tone: "green" },
      { label: "Ball recoveries", value: 90, tone: "green" },
      { label: "Box entries", value: 42, tone: "amber" },
    ],
    performanceSplit: [
      { category: "Attacking", current: 58, benchmark: 51 },
      { category: "Passing", current: 84, benchmark: 69 },
      { category: "Defending", current: 90, benchmark: 72 },
      { category: "Physical", current: 78, benchmark: 68 },
    ],
    trend: createTrend(76, 5),
    marketTrend: createMarketTrend(5.4, 0.38),
    matchLogs: createMatchLogs(["Braga", "Sporting", "Boavista", "Gil Vicente", "Benfica"], 5),
    similarityIds: ["p7", "p9", "p10"],
    scoutNotes: [
      { author: "N. Rossi", note: "One of the cleanest pivots in the data for sides needing immediate structure.", time: "Today" },
      { author: "T. Verhoeven", note: "Worth live view against a more transition-heavy opponent.", time: "3 days ago" },
    ],
  }),
  buildPlayer({
    id: "p3",
    slug: "rafik-belghali",
    name: "Rafik Belghali",
    age: 23,
    nationality: "Algeria",
    club: "KV Mechelen",
    league: "Belgian Pro League",
    position: "W",
    secondaryPositions: ["FB", "AM"],
    minutes: 2021,
    marketValueM: 5.2,
    scoutingScore: 91,
    form: "Rising",
    contractExpiry: "2026-06-30",
    preferredFoot: "Right",
    heightCm: 175,
    status: "priority",
    archetype: "Direct chance creator",
    summary: "Explosive wide player who creates separation quickly and repeatedly drives high-value entries from the touchline.",
    strengths: ["1v1 separation", "Penalty-area creation", "Change of pace", "Final-third productivity"],
    concerns: ["End-product variance", "Defensive workload consistency"],
    report: {
      technical: "Very quick set-up touches and can create crossing windows off both feet. Still inconsistent on final action under pressure.",
      tactical: "Best starting wide and attacking the half-space late. Needs a structure that protects him in deeper defending phases.",
      physical: "Sharp accelerator with enough repeat burst to threaten over 90 minutes.",
      mental: "Confident and proactive; does not hide after unsuccessful actions.",
      recommendation: "Review",
    },
    tags: ["Chance creation", "Wide threat", "Value gap"],
    radar: [
      { subject: "Progression", value: 86 },
      { subject: "Creation", value: 91 },
      { subject: "Defending", value: 47 },
      { subject: "Physical", value: 82 },
      { subject: "Decision-making", value: 72 },
      { subject: "Press resistance", value: 79 },
    ],
    percentiles: [
      { label: "Successful dribbles", value: 95, tone: "blue" },
      { label: "Shot assists", value: 89, tone: "green" },
      { label: "Progressive carries", value: 92, tone: "blue" },
      { label: "Crosses completed", value: 71, tone: "amber" },
      { label: "Defensive actions", value: 39, tone: "amber" },
    ],
    performanceSplit: [
      { category: "Attacking", current: 91, benchmark: 69 },
      { category: "Passing", current: 76, benchmark: 67 },
      { category: "Defending", current: 48, benchmark: 58 },
      { category: "Physical", current: 82, benchmark: 71 },
    ],
    trend: createTrend(78, 8),
    marketTrend: createMarketTrend(3.6, 0.32),
    matchLogs: createMatchLogs(["Genk", "Gent", "Anderlecht", "Standard", "Antwerp"], 9),
    similarityIds: ["p6", "p8", "p11"],
    scoutNotes: [
      { author: "J. Holzer", note: "Immediate watchlist candidate for teams needing direct right-side chance creation.", time: "5h ago" },
      { author: "M. Silva", note: "Needs context fit. Better in aggressive front-foot model than deep block.", time: "Last week" },
    ],
  }),
  buildPlayer({
    id: "p4",
    slug: "ringo-meerveld",
    name: "Ringo Meerveld",
    age: 22,
    nationality: "Netherlands",
    club: "Willem II",
    league: "Eredivisie",
    position: "AM",
    secondaryPositions: ["CM", "W"],
    minutes: 2310,
    marketValueM: 4.8,
    scoutingScore: 88,
    form: "Stable",
    contractExpiry: "2026-06-30",
    preferredFoot: "Left",
    heightCm: 180,
    status: "shortlist",
    archetype: "Creative connector",
    summary: "Left-footed creator who links midfield to attack through disguised passing and calm receiving between lines.",
    strengths: ["Between-line receiving", "Through balls", "Tempo shifts", "Half-space combinations"],
    concerns: ["Contact resistance", "Defensive range"],
    report: {
      technical: "High-end first touch and disguises release angles well. Final-third creativity is his standout trait.",
      tactical: "Needs a possession structure and runners ahead of him. Better as a narrow ten or advanced eight than as a winger.",
      physical: "Average frame and not dominant in contact, but agile enough to escape central pressure.",
      mental: "Composed and sees early pictures. Decision-making tends to improve as game state stabilises.",
      recommendation: "Watch",
    },
    tags: ["Creator", "Under market", "Technical upside"],
    radar: [
      { subject: "Progression", value: 82 },
      { subject: "Creation", value: 93 },
      { subject: "Defending", value: 42 },
      { subject: "Physical", value: 61 },
      { subject: "Decision-making", value: 84 },
      { subject: "Press resistance", value: 83 },
    ],
    percentiles: [
      { label: "Key passes", value: 94, tone: "blue" },
      { label: "Passes into box", value: 91, tone: "green" },
      { label: "Turn resistance", value: 86, tone: "green" },
      { label: "Defensive duels", value: 34, tone: "amber" },
      { label: "Shot volume", value: 63 },
    ],
    performanceSplit: [
      { category: "Attacking", current: 82, benchmark: 66 },
      { category: "Passing", current: 91, benchmark: 71 },
      { category: "Defending", current: 40, benchmark: 57 },
      { category: "Physical", current: 61, benchmark: 67 },
    ],
    trend: createTrend(75, 6),
    marketTrend: createMarketTrend(3.2, 0.28),
    matchLogs: createMatchLogs(["Go Ahead", "NEC", "PSV", "Sparta", "Ajax"], 13),
    similarityIds: ["p2", "p10", "p11"],
    scoutNotes: [
      { author: "S. Ainsworth", note: "Best suited to sides with the ball. Not the right fit for pure transition role.", time: "1 day ago" },
      { author: "K. Laurent", note: "Worth compare against own academy profile before moving further.", time: "4 days ago" },
    ],
  }),
  buildPlayer({
    id: "p5",
    slug: "fedde-leysen",
    name: "Fedde Leysen",
    age: 21,
    nationality: "Belgium",
    club: "Union SG",
    league: "Belgian Pro League",
    position: "CB",
    secondaryPositions: ["FB"],
    minutes: 2114,
    marketValueM: 6.1,
    scoutingScore: 87,
    form: "Rising",
    contractExpiry: "2027-06-30",
    preferredFoot: "Left",
    heightCm: 187,
    status: "shortlist",
    archetype: "Front-foot left centre-back",
    summary: "Young left-sided centre-back with clean passing angles, good anticipation, and a profile that scales into possession teams.",
    strengths: ["Defensive anticipation", "Diagonal distribution", "Aerial timing", "Front-foot stepping"],
    concerns: ["Recovery pace in open field", "Aggressive stepping risk"],
    report: {
      technical: "Comfortable opening body to play forward and can break first line with left foot.",
      tactical: "Reads pressing lanes well and likes to step into midfield duels. Needs cover if used in very aggressive line heights.",
      physical: "Good frame and timing. Top-end pace is adequate rather than elite.",
      mental: "Assertive defender who looks comfortable leading the line despite age.",
      recommendation: "Review",
    },
    tags: ["Left-sided CB", "Development upside", "Possession fit"],
    radar: [
      { subject: "Progression", value: 79 },
      { subject: "Creation", value: 51 },
      { subject: "Defending", value: 89 },
      { subject: "Physical", value: 81 },
      { subject: "Decision-making", value: 82 },
      { subject: "Press resistance", value: 74 },
    ],
    percentiles: [
      { label: "Interceptions", value: 88, tone: "green" },
      { label: "Aerial duels", value: 84, tone: "green" },
      { label: "Progressive passes", value: 78, tone: "blue" },
      { label: "Recovery speed", value: 63, tone: "amber" },
      { label: "Clearances", value: 80 },
    ],
    performanceSplit: [
      { category: "Attacking", current: 44, benchmark: 42 },
      { category: "Passing", current: 79, benchmark: 66 },
      { category: "Defending", current: 89, benchmark: 72 },
      { category: "Physical", current: 80, benchmark: 71 },
    ],
    trend: createTrend(73, 4),
    marketTrend: createMarketTrend(4.6, 0.34),
    matchLogs: createMatchLogs(["Club Brugge", "Gent", "Genk", "Antwerp", "Standard"], 16),
    similarityIds: ["p1", "p9", "p12"],
    scoutNotes: [
      { author: "E. Vandenberg", note: "High-value development defender if the physical runway is there.", time: "Today" },
      { author: "D. Yates", note: "Could jump quickly once minutes accumulate in a more dominant side.", time: "2 days ago" },
    ],
  }),
  buildPlayer({
    id: "p6",
    slug: "stelios-andreou",
    name: "Stelios Andreou",
    age: 22,
    nationality: "Cyprus",
    club: "Charleroi",
    league: "Belgian Pro League",
    position: "CB",
    secondaryPositions: ["DM"],
    minutes: 2395,
    marketValueM: 5.7,
    scoutingScore: 84,
    form: "Stable",
    contractExpiry: "2026-06-30",
    preferredFoot: "Right",
    heightCm: 188,
    status: "monitor",
    archetype: "Aerial stopper with range",
    summary: "High-volume duel winner with useful cover range and enough passing to support a mid-block possession structure.",
    strengths: ["Aerial dominance", "Recovery defending", "Defensive volume", "Cross-box coverage"],
    concerns: ["Tight-space passing", "Progression under heavy press"],
    report: {
      technical: "Simple rather than expansive distributor, but secure on routine actions.",
      tactical: "Covers large spaces well and suits teams that defend front-foot but still face transition moments.",
      physical: "Strong profile with good stride speed over distance.",
      mental: "Competitive and engaged; can get drawn into aggressive duels too early.",
      recommendation: "Price Check",
    },
    tags: ["Aerial profile", "Defensive floor"],
    radar: [
      { subject: "Progression", value: 58 },
      { subject: "Creation", value: 38 },
      { subject: "Defending", value: 91 },
      { subject: "Physical", value: 85 },
      { subject: "Decision-making", value: 71 },
      { subject: "Press resistance", value: 57 },
    ],
    percentiles: [
      { label: "Aerials won", value: 96, tone: "green" },
      { label: "Blocks + clearances", value: 90, tone: "green" },
      { label: "Recovery actions", value: 84, tone: "blue" },
      { label: "Progressive passing", value: 52, tone: "amber" },
      { label: "Turn resistance", value: 41, tone: "amber" },
    ],
    performanceSplit: [
      { category: "Attacking", current: 35, benchmark: 42 },
      { category: "Passing", current: 58, benchmark: 66 },
      { category: "Defending", current: 91, benchmark: 72 },
      { category: "Physical", current: 86, benchmark: 71 },
    ],
    trend: createTrend(71, 4),
    marketTrend: createMarketTrend(4.4, 0.22),
    matchLogs: createMatchLogs(["Anderlecht", "Genk", "Cercle", "Brugge", "Gent"], 18),
    similarityIds: ["p5", "p12", "p1"],
    scoutNotes: [
      { author: "P. Möller", note: "Floor is strong. Ceiling depends on whether build-up can scale.", time: "Yesterday" },
    ],
  }),
  buildPlayer({
    id: "p7",
    slug: "martim-neto",
    name: "Martim Neto",
    age: 22,
    nationality: "Portugal",
    club: "Rio Ave",
    league: "Primeira Liga",
    position: "CM",
    secondaryPositions: ["DM", "AM"],
    minutes: 1930,
    marketValueM: 4.3,
    scoutingScore: 86,
    form: "Rising",
    contractExpiry: "2026-06-30",
    preferredFoot: "Left",
    heightCm: 179,
    status: "shortlist",
    archetype: "Progressive central connector",
    summary: "Left-footed midfielder who can progress the game both by carry and pass and offers technical control in tight structures.",
    strengths: ["Tempo shifts", "Switches of play", "Scanning", "Press resistance"],
    concerns: ["Explosiveness", "Final-third defensive coverage"],
    report: {
      technical: "Very clean on the half-turn and plays forward early. Passing range is a standout differentiator.",
      tactical: "Fits in possession sides using a double pivot or advanced 8. Less valuable in low-possession environments.",
      physical: "Mobile enough but not a pure athlete. Relies on timing more than burst.",
      mental: "Plays with maturity and rarely rushes his next action.",
      recommendation: "Review",
    },
    tags: ["Left foot", "Possession fit", "Contract watch"],
    radar: [
      { subject: "Progression", value: 88 },
      { subject: "Creation", value: 78 },
      { subject: "Defending", value: 61 },
      { subject: "Physical", value: 64 },
      { subject: "Decision-making", value: 87 },
      { subject: "Press resistance", value: 89 },
    ],
    percentiles: [
      { label: "Progressive passes", value: 93, tone: "blue" },
      { label: "Line-breaking receptions", value: 88, tone: "green" },
      { label: "Pass completion", value: 91, tone: "green" },
      { label: "Ball recoveries", value: 62, tone: "amber" },
      { label: "Carry volume", value: 76 },
    ],
    performanceSplit: [
      { category: "Attacking", current: 68, benchmark: 57 },
      { category: "Passing", current: 91, benchmark: 71 },
      { category: "Defending", current: 61, benchmark: 60 },
      { category: "Physical", current: 64, benchmark: 66 },
    ],
    trend: createTrend(74, 5),
    marketTrend: createMarketTrend(3.1, 0.3),
    matchLogs: createMatchLogs(["Porto", "Arouca", "Braga", "Estoril", "Benfica"], 22),
    similarityIds: ["p2", "p4", "p10"],
    scoutNotes: [
      { author: "R. Delaunay", note: "If the brief is control, he is one of the cleanest affordable midfielders in range.", time: "6h ago" },
    ],
  }),
  buildPlayer({
    id: "p8",
    slug: "yasin-ozdemir",
    name: "Yasin Özdemir",
    age: 20,
    nationality: "Turkey",
    club: "Kasımpaşa",
    league: "Turkish Super Lig",
    position: "ST",
    secondaryPositions: ["W"],
    minutes: 1812,
    marketValueM: 4.9,
    scoutingScore: 90,
    form: "Rising",
    contractExpiry: "2028-06-30",
    preferredFoot: "Right",
    heightCm: 183,
    status: "priority",
    archetype: "Transition-running striker",
    summary: "Young striker with good depth running, growing finishing output, and profile elasticity to play alone or off a second attacker.",
    strengths: ["Running behind", "Shot volume", "Transition threat", "Explosive separation"],
    concerns: ["Back-to-goal craft", "Aerial timing"],
    report: {
      technical: "Finishing has improved and he gets to shots quickly. Hold-up play is still raw.",
      tactical: "Best in a team that attacks space. Less convincing when asked to pin and combine for long spells.",
      physical: "Fast and springy, with clear development runway as frame fills out.",
      mental: "Attacks moments aggressively and responds well to repeated high-risk actions.",
      recommendation: "Watch",
    },
    tags: ["U21", "High upside", "Transition"],
    radar: [
      { subject: "Progression", value: 73 },
      { subject: "Creation", value: 58 },
      { subject: "Defending", value: 34 },
      { subject: "Physical", value: 87 },
      { subject: "Decision-making", value: 69 },
      { subject: "Press resistance", value: 55 },
    ],
    percentiles: [
      { label: "xG/90", value: 91, tone: "green" },
      { label: "Runs behind", value: 95, tone: "blue" },
      { label: "Shot volume", value: 88, tone: "green" },
      { label: "Link play", value: 44, tone: "amber" },
      { label: "Aerial duels", value: 38, tone: "amber" },
    ],
    performanceSplit: [
      { category: "Attacking", current: 89, benchmark: 68 },
      { category: "Passing", current: 49, benchmark: 58 },
      { category: "Defending", current: 34, benchmark: 44 },
      { category: "Physical", current: 87, benchmark: 70 },
    ],
    trend: createTrend(80, 7),
    marketTrend: createMarketTrend(2.9, 0.36),
    matchLogs: createMatchLogs(["Trabzonspor", "Fenerbahçe", "Rizespor", "Samsunspor", "Galatasaray"], 25),
    similarityIds: ["p3", "p11", "p1"],
    scoutNotes: [
      { author: "B. Kaya", note: "One of the more attractive growth bets if you are comfortable buying unfinished striker play.", time: "Today" },
      { author: "A. Nordin", note: "Recommend live check for off-ball intensity when team cannot dominate territory.", time: "2 days ago" },
    ],
  }),
  buildPlayer({
    id: "p9",
    slug: "bartosz-zielinski",
    name: "Bartosz Zieliński",
    age: 23,
    nationality: "Poland",
    club: "PAOK",
    league: "Greek Super League",
    position: "GK",
    secondaryPositions: ["CB"],
    minutes: 2520,
    marketValueM: 3.9,
    scoutingScore: 80,
    form: "Stable",
    contractExpiry: "2026-06-30",
    preferredFoot: "Right",
    heightCm: 191,
    status: "watch",
    archetype: "Proactive distribution goalkeeper",
    summary: "Goalkeeper with distribution upside and positive box actions, though shot-stopping is still volatile across game states.",
    strengths: ["Distribution range", "Cross claiming", "Starting position"],
    concerns: ["Low-shot rhythm", "Near-post handling variance"],
    report: {
      technical: "Passing is above average for the market bracket. Handling remains the swing trait.",
      tactical: "Useful if you want to hold a higher line and start cleanly from the back.",
      physical: "Good size and movement profile, particularly on aggressive claims.",
      mental: "Confident on the ball but can overforce difficult restarts.",
      recommendation: "Pass",
    },
    tags: ["GK market", "Distribution"],
    radar: [
      { subject: "Shot stop", value: 68 },
      { subject: "Distribution", value: 86 },
      { subject: "Claims", value: 82 },
      { subject: "Sweep", value: 79 },
      { subject: "Composure", value: 74 },
      { subject: "Reflex", value: 66 },
    ],
    percentiles: [
      { label: "Long pass accuracy", value: 90, tone: "blue" },
      { label: "Claims", value: 84, tone: "green" },
      { label: "Post-shot xG saved", value: 57, tone: "amber" },
      { label: "Sweeper actions", value: 82, tone: "green" },
      { label: "Save %", value: 61 },
    ],
    performanceSplit: [
      { category: "Attacking", current: 35, benchmark: 26 },
      { category: "Passing", current: 86, benchmark: 54 },
      { category: "Defending", current: 71, benchmark: 65 },
      { category: "Physical", current: 78, benchmark: 68 },
    ],
    trend: createTrend(69, 3),
    marketTrend: createMarketTrend(2.7, 0.24),
    matchLogs: createMatchLogs(["AEK", "Panathinaikos", "Olympiakos", "Aris", "Lamia"], 27),
    similarityIds: ["p5", "p6", "p12"],
    scoutNotes: [{ author: "F. Keller", note: "Good stylistic fit for possession build-up, but not yet a no-doubt shot stopper.", time: "Yesterday" }],
  }),
  buildPlayer({
    id: "p10",
    slug: "leo-kristensen",
    name: "Leo Kristensen",
    age: 23,
    nationality: "Denmark",
    club: "AZ Alkmaar",
    league: "Eredivisie",
    position: "CM",
    secondaryPositions: ["AM", "DM"],
    minutes: 2160,
    marketValueM: 8.2,
    scoutingScore: 85,
    form: "Cooling",
    contractExpiry: "2027-06-30",
    preferredFoot: "Right",
    heightCm: 182,
    status: "monitor",
    archetype: "High-volume midfielder",
    summary: "Dynamic all-phase midfielder with useful pressing and carrying numbers, but the value may be approaching fair price.",
    strengths: ["Work rate", "Ball carrying", "Counterpressing", "Late runs"],
    concerns: ["Price inflation", "Short-passing security under pressure"],
    report: {
      technical: "Functional rather than elite passer, but offers volume and vertical intent.",
      tactical: "Useful as an aggressive eight. Less convincing as the sole rhythm-setter.",
      physical: "Strong engine and enough athleticism to play at higher intensity.",
      mental: "Competitive and relentless, though occasionally rushes actions in possession.",
      recommendation: "Price Check",
    },
    tags: ["Fair value", "High motor"],
    radar: [
      { subject: "Progression", value: 79 },
      { subject: "Creation", value: 70 },
      { subject: "Defending", value: 74 },
      { subject: "Physical", value: 81 },
      { subject: "Decision-making", value: 68 },
      { subject: "Press resistance", value: 70 },
    ],
    percentiles: [
      { label: "Carries", value: 84, tone: "blue" },
      { label: "Counterpress actions", value: 89, tone: "green" },
      { label: "Box arrivals", value: 78, tone: "green" },
      { label: "Pass retention", value: 62, tone: "amber" },
      { label: "Value gap", value: 48, tone: "amber" },
    ],
    performanceSplit: [
      { category: "Attacking", current: 71, benchmark: 62 },
      { category: "Passing", current: 69, benchmark: 70 },
      { category: "Defending", current: 76, benchmark: 64 },
      { category: "Physical", current: 82, benchmark: 68 },
    ],
    trend: createTrend(72, 3),
    marketTrend: createMarketTrend(5.8, 0.44),
    matchLogs: createMatchLogs(["Ajax", "PSV", "Twente", "Go Ahead", "Heerenveen"], 31),
    similarityIds: ["p2", "p4", "p7"],
    scoutNotes: [{ author: "G. Vos", note: "Profile is real. Question is value, not talent.", time: "This week" }],
  }),
  buildPlayer({
    id: "p11",
    slug: "souleymane-barry",
    name: "Souleymane Barry",
    age: 21,
    nationality: "Senegal",
    club: "Famalicão",
    league: "Primeira Liga",
    position: "W",
    secondaryPositions: ["ST", "AM"],
    minutes: 1746,
    marketValueM: 3.8,
    scoutingScore: 83,
    form: "Rising",
    contractExpiry: "2027-06-30",
    preferredFoot: "Left",
    heightCm: 178,
    status: "watch",
    archetype: "Vertical inside forward",
    summary: "Young attacker with speed and shot access, but the overall game still needs refinement.",
    strengths: ["Verticality", "Open-field speed", "Penalty box arrivals"],
    concerns: ["Final-pass selection", "Defensive discipline"],
    report: {
      technical: "Can generate his own shots but remains inconsistent in the final pass.",
      tactical: "Works best arriving from wide into central lanes rather than being the primary creator.",
      physical: "Very good acceleration and enough flexibility to attack different spaces.",
      mental: "Positive, direct, and still learning game management.",
      recommendation: "Watch",
    },
    tags: ["Development wing", "High variance"],
    radar: [
      { subject: "Progression", value: 81 },
      { subject: "Creation", value: 59 },
      { subject: "Defending", value: 33 },
      { subject: "Physical", value: 85 },
      { subject: "Decision-making", value: 58 },
      { subject: "Press resistance", value: 67 },
    ],
    percentiles: [
      { label: "Runs behind", value: 89, tone: "blue" },
      { label: "Touches in box", value: 84, tone: "green" },
      { label: "xG/90", value: 78, tone: "green" },
      { label: "Final-ball accuracy", value: 41, tone: "amber" },
      { label: "Defensive actions", value: 28, tone: "amber" },
    ],
    performanceSplit: [
      { category: "Attacking", current: 84, benchmark: 65 },
      { category: "Passing", current: 55, benchmark: 62 },
      { category: "Defending", current: 33, benchmark: 48 },
      { category: "Physical", current: 86, benchmark: 69 },
    ],
    trend: createTrend(70, 6),
    marketTrend: createMarketTrend(2.5, 0.25),
    matchLogs: createMatchLogs(["Portimonense", "Braga", "Sporting", "Casa Pia", "Farense"], 34),
    similarityIds: ["p3", "p8", "p4"],
    scoutNotes: [{ author: "Y. Mbaye", note: "Worth tracking; upside depends on how quickly the decision-making sharpens.", time: "2 days ago" }],
  }),
  buildPlayer({
    id: "p12",
    slug: "mattias-lund",
    name: "Mattias Lund",
    age: 24,
    nationality: "Sweden",
    club: "AEK Athens",
    league: "Greek Super League",
    position: "FB",
    secondaryPositions: ["CB", "W"],
    minutes: 2077,
    marketValueM: 4.6,
    scoutingScore: 82,
    form: "Stable",
    contractExpiry: "2026-06-30",
    preferredFoot: "Left",
    heightCm: 183,
    status: "watch",
    archetype: "Defensive-sided fullback",
    summary: "Reliable left-back with a solid defensive floor and enough crossing to project into more pragmatic squads.",
    strengths: ["Defensive positioning", "Crossing volume", "Aerial support"],
    concerns: ["Burst in possession", "Top-end creativity"],
    report: {
      technical: "Crossing is repeatable and contact quality is good. Not a natural dribbler.",
      tactical: "Useful in teams that value balance from the fullback slot more than pure attacking output.",
      physical: "Solid frame with good durability, though not a true explosive runner.",
      mental: "Stable performer with low-error profile.",
      recommendation: "Price Check",
    },
    tags: ["Defensive fullback", "Reliable floor"],
    radar: [
      { subject: "Progression", value: 62 },
      { subject: "Creation", value: 66 },
      { subject: "Defending", value: 82 },
      { subject: "Physical", value: 73 },
      { subject: "Decision-making", value: 79 },
      { subject: "Press resistance", value: 64 },
    ],
    percentiles: [
      { label: "Defensive duels", value: 83, tone: "green" },
      { label: "Cross completion", value: 72, tone: "blue" },
      { label: "Availability", value: 88, tone: "green" },
      { label: "Progressive carries", value: 49, tone: "amber" },
      { label: "Shot creation", value: 44, tone: "amber" },
    ],
    performanceSplit: [
      { category: "Attacking", current: 58, benchmark: 54 },
      { category: "Passing", current: 67, benchmark: 65 },
      { category: "Defending", current: 82, benchmark: 67 },
      { category: "Physical", current: 74, benchmark: 68 },
    ],
    trend: createTrend(68, 3),
    marketTrend: createMarketTrend(3.6, 0.18),
    matchLogs: createMatchLogs(["Panathinaikos", "PAOK", "Olympiakos", "Aris", "Lamia"], 39),
    similarityIds: ["p5", "p6", "p1"],
    scoutNotes: [{ author: "I. Petrou", note: "Strong floor pick, but not the same upside as the more progressive options.", time: "5 days ago" }],
  }),
];

export const dashboardKpis: KPI[] = [
  { label: "Players tracked", value: "1,248", delta: "+7.2% vs last month", tone: "blue" },
  { label: "New high-potential players", value: "38", delta: "+11 this week", tone: "green" },
  { label: "Average scouting score", value: "83.4", delta: "+1.8 pts in active shortlist", tone: "amber" },
  { label: "Matches analysed", value: "264", delta: "17 live reports this week", tone: "blue" },
];

export const activityFeed: ActivityItem[] = [
  { title: "Priority tag added to Mika van den Bos", subtitle: "Fullback recruitment board / Eredivisie cluster", time: "12 min ago", type: "note" },
  { title: "Shortlist memo exported for João Serrano", subtitle: "Midfield anchor board / January window", time: "44 min ago", type: "report" },
  { title: "Live assignment created: Turkish Super Lig forwards", subtitle: "Assigned to Y. Mbaye", time: "2 h ago", type: "assignment" },
  { title: "Risk note updated on Bartosz Zieliński", subtitle: "Goalkeeper market watch", time: "Yesterday", type: "note" },
];

export const watchlistTasks: TaskItem[] = [
  { title: "Live view João Serrano vs Sporting", owner: "N. Rossi", due: "Fri 19 Apr", priority: "High" },
  { title: "Compile winger memo pack for Belgium cluster", owner: "A. Mertens", due: "Mon 22 Apr", priority: "Medium" },
  { title: "Check contract leverage for Martim Neto", owner: "L. De Smet", due: "Tue 23 Apr", priority: "Low" },
];

export const shortlists: Shortlist[] = [
  {
    id: "s1",
    name: "U23 midfield targets",
    count: 7,
    averageAge: 21.7,
    averageValueM: 5.4,
    updatedAt: "Today",
    priority: "Critical",
    owner: "Recruitment lead",
    tags: ["Midfield", "U23", "Summer"],
    playerIds: ["p2", "p4", "p7", "p10"],
    note: "Focus on players who can start games by autumn, not just developmental depth.",
  },
  {
    id: "s2",
    name: "Left-backs with high progression",
    count: 5,
    averageAge: 22.6,
    averageValueM: 5.1,
    updatedAt: "Yesterday",
    priority: "Live",
    owner: "Scouting ops",
    tags: ["Fullback", "Progression", "Value"],
    playerIds: ["p1", "p12", "p5"],
    note: "Board for clubs needing immediate width and sustainable carry volume.",
  },
  {
    id: "s3",
    name: "Transition forwards outside Big Five",
    count: 6,
    averageAge: 21.9,
    averageValueM: 4.7,
    updatedAt: "2 days ago",
    priority: "Exploratory",
    owner: "Forward scout",
    tags: ["ST", "W", "Non-Big5"],
    playerIds: ["p3", "p8", "p11"],
    note: "Used when game model demands speed and direct running more than settled build-up craft.",
  },
];

export const reportBlocks: ReportBlock[] = [
  { id: "summary", label: "Player Summary", description: "Executive overview with fit, price, and current recommendation." },
  { id: "stats", label: "Stats Snapshot", description: "KPI module with percentile bars and trend call-outs." },
  { id: "strengths", label: "Strengths / Weaknesses", description: "Clear recruitment positives and red flags." },
  { id: "notes", label: "Scout Notes", description: "Attach qualitative notes from live reports and video review." },
  { id: "recommendation", label: "Decision Call", description: "Final call: pursue, review, watch, price check, or pass." },
];

export const teamCards: TeamCard[] = [
  { name: "Royal Antwerp", league: "Belgian Pro League", style: "4-2-3-1 / front-foot", pressing: 77, possession: 55, averageAge: 24.8 },
  { name: "SC Braga", league: "Primeira Liga", style: "4-4-2 diamond", pressing: 72, possession: 58, averageAge: 25.3 },
  { name: "FC Twente", league: "Eredivisie", style: "4-3-3 / high width", pressing: 74, possession: 57, averageAge: 24.5 },
];

export const trendingPlayers = players.slice(0, 4);

export const ageValueScatterData = players.map((player) => ({
  name: player.name,
  age: player.age,
  value: player.marketValueM,
  score: player.scoutingScore,
  league: player.league,
}));

export const performanceTrendData = [
  { label: "Aug", scouting: 74, benchmark: 69 },
  { label: "Sep", scouting: 76, benchmark: 70 },
  { label: "Oct", scouting: 79, benchmark: 71 },
  { label: "Nov", scouting: 81, benchmark: 72 },
  { label: "Dec", scouting: 83, benchmark: 73 },
  { label: "Jan", scouting: 85, benchmark: 74 },
];

export const positionDistributionData = (Object.entries(
  players.reduce<Record<PlayerPosition, number>>((acc, player) => {
    acc[player.position] = (acc[player.position] || 0) + 1;
    return acc;
  }, {} as Record<PlayerPosition, number>)
) as [PlayerPosition, number][]).map(([position, value]) => ({ position, value }));

export const topPerformersByRole = ["FB", "DM", "W", "CB"].map((role) =>
  players
    .filter((player) => player.position === role)
    .sort((a, b) => b.scoutingScore - a.scoutingScore)[0]
).filter(Boolean) as Player[];

export function getPlayerBySlug(slug: string) {
  return players.find((player) => player.slug === slug);
}

export function getPlayerById(id: string) {
  return players.find((player) => player.id === id);
}

export function getSimilarPlayers(player: Player) {
  return player.similarityIds.map((id) => getPlayerById(id)).filter(Boolean) as Player[];
}

export function getShortlistById(id: string) {
  return shortlists.find((shortlist) => shortlist.id === id);
}
